spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: bank_api
security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30
logging:
  level:
    root: ERROR
    ru.medvedev.bankservice.web.: WARN
  pattern:
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: logs/bank-service.log
